### ISSUE TITLE
是否考虑使用ContentProvider初始化获取Application的上下文呢？

### ISSUE THREAD

**Issue by lihuiqiang123** [biubiuqiu0/flow-event-bus#2]
Lib库使用ContentProvider初始化全局Context上下问，就省去了在Application中初始化过程，用起来岂不是更加丝滑。

**Comment by biubiuqiu0** [comment]
理论上 ContentProvider 会有初始化的性能问题。因此不是很建议使用这种方式。

**Comment by lihuiqiang123** [comment]
ContentProvider 在 Application#onCreate 之前初始化，确实会耗时，对于应用启动时间控制比较严格的确实会有性能问题。另外，ContentProvider 初始化无法解决三方库初始化过程中的依赖问题。
