### ISSUE TITLE
考虑 postEvent 增加 EventKey 逻辑吗

### ISSUE THREAD

**Issue by daiwenbo88** [biubiuqiu0/flow-event-bus#3]
postEvent 增加 EventKey 逻辑，这样发送发送基本数据类型事件，订阅那边就可以根据key 来进行订阅了

**Comment by biubiuqiu0** [comment]
最开始是有这样的设计的，在实际使用中 团队内部还是希望事件名称能够明确，如果以String为key ，则任何模块都能监听，这个依赖关系就会较为隐匿。
