### ISSUE TITLE
与生命周期无关的事件回调

### ISSUE THREAD

**Issue by rainfoam** [biubiuqiu0/flow-event-bus#4]
App的Lifecycle生命周期其实监听的是Activity的生命周期，您封装的全局App的事件代码其实还是会跟Activity生命周期相关，必须回调onStart才会收到事件。如果想收到全局与生命周期无关的事件，是否可以考虑添加类似下面的封装：

```
//监听App Scope 事件,但是不关心Application的生命周期
@MainThread
inline fun <reified T> LifecycleOwner.observeEventWithoutAppLifecycle(
    coroutineScope: CoroutineScope = ProcessLifecycleOwner.get().lifecycleScope,
    isSticky: Boolean = false,
    noinline onReceived: (T) -> Unit
): Job {
    return observeEvent(
        coroutineScope,
        isSticky,
        onReceived
    )
}
```
谢谢

**Comment by biubiuqiu0** [comment]
我记得我封装的有
`observeEvent<GlobalEvent>(lifecycleScope) { value ->
            Log.d(TAG, "MainActivity received GlobalEvent  :${value.name}")
        }`   
  看看是不是调用错了.     监听方法不要使用 LifecycleOwner 的扩展方法那个。
