### ISSUE TITLE
多个事件类型继承同一个基类，我在注册观察者的时候可否通过这个基类进行注册，发送的时候发的是具体的子类

### ISSUE THREAD

**Issue by artillerymans** [biubiuqiu0/flow-event-bus#7]
`接收：observeEvent<BaseEvent>(){}
 发送 ：postEvent(SetHRConfigEvent())`
貌似这样收不到， SetHRConfigEvent继承 BaseEvent

**Comment by biubiuqiu0** [comment]
是的，由于目前内部是用 字符串做key，因此这种继承关系的并不能接收到。  后面可以改成 class做key，分发时做类型判断。
